version: '3.8'

services:
  clientes-react:
    build: .
    container_name: clientes-app
    ports:
      - "8080:8080" # Swagger y API
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      # Verificamos que el motor reactivo esté respondiendo
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - reactive-net

networks:
  reactive-net:
    driver: bridge