version: '3.8'

services:
  # 1. Backend CRUD
  backend-crud:
    image: crudreac_app:latest
    ports:
      - "9091:8081"

  # 2. Backend Clientes
  backend-clientes:
    image: clientes-react-back_clientes-react:latest
    ports:
      - "8080:8080"

  # 3. Frontend (Levanta al final)
  frontend:
    image: clientes-react-front_frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend-crud
      - backend-clientes

networks:
  default:
    name: mi-red-local