-- DDL para crear las tablas
-- -----------------------------------

-- DROP TABLE si existen para evitar errores al reiniciar
DROP TABLE IF EXISTS producto;
DROP TABLE IF EXISTS categoria;

-- 1. CREACIÓN DE LA TABLA CATEGORIA
CREATE TABLE categoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Clave primaria autogenerada
    nombre VARCHAR(255) NOT NULL UNIQUE
);

-- 2. CREACIÓN DE LA TABLA PRODUCTO
CREATE TABLE producto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Clave primaria autogenerada
    nombre VARCHAR(255) NOT NULL,

    -- Clave foránea que apunta a la tabla categoria
    categoria_id BIGINT NOT NULL,

    precio_unitario DOUBLE NOT NULL,
    stock INT NOT NULL,

    -- Definición de la relación de clave foránea
    CONSTRAINT fk_producto_categoria
        FOREIGN KEY (categoria_id)
        REFERENCES categoria(id)
        ON DELETE RESTRICT -- Evita borrar una categoría si tiene productos asociados
);