version: '3.8'

services:
  app:
    build: .
    ports:
      # Puerto externo (9091) : Puerto interno (8081)
      -"9091:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge